plan:
  targetPhase: setup
  defaultInstanceMode: immediate
  preflight:
    description: Deploy base infra like Redis/NATS.
    selector:
      matchLabels:
        phase: preflight
    onFailure:
      action: raise
      spec:
        message: 
        - "Preflight checks failed, please check the logs."
        notify:
          email: oncall@team.com
          slack: "#ops-alerts"
  initialization:
    description: Generate IDs, slugs, and other initial data.
    selector:
      matchLabels:
        phase: ${LOCAL_INIT_GROUP:initialization}
    waitFor:
      phases:
        - preflight
      timeout: 300ms        
    retry:
      maxAttempts: ${MAX_INITIALIZATION_ATTEMPTS:5}
    onFailure:
      action: continue
      spec:
        message: 
        - "Initialization failed, please check the logs."
        - "We will continue with defaults."
        labels:
          initialization: defaults
    onSuccess:
      spec:
        message: 
        - "Initialization completed successfully."
        notify:
          email: oncall@team.com
  setup:
    description: Set up game board and initial state.
    selector:
      matchLabels:
        phase: setup
    waitFor: 
      phases: [initialization]
    retry:
      maxAttempts: "10"
  lazy:
    description: Deploy squads and other resources as needed.
    selector:
      matchLabels:
        phase: lazy
    instanceMode: onUse
